USE [GreenWerxDev]
GO

INSERT INTO [dbo].[Settings]
           ([UUID]
           ,[Value]
           ,[Type]
           ,[AppType]
           ,[SettingClass]
           ,[AccountUUID]
           ,[Active]
           ,[CreatedBy]
           ,[DateCreated]
           ,[Deleted]
           ,[GUUID]
           ,[GuuidType]
           ,[Image]
           ,[Name]
           ,[NSFW]
           ,[Private]
           ,[RoleOperation]
           ,[RoleWeight]
           ,[SortOrder]
           ,[Status]
           ,[UUIDType]
           ,[UUParentID]
           ,[UUParentIDType])
     VALUES
           ('greenwerxlocaluuid'						--[UUID]
           ,'ec8664adfdf345c29b555c3c47fd0498'		   --[Value]
           ,'string'								   --[Type]
           ,'web'									   --[AppType]
           ,'setting'								   --[SettingClass]
           ,'ec8664adfdf345c29b555c3c47fd0498'		   --[AccountUUID]
           ,1										   --[Active]
           ,'test'									   --[CreatedBy]
           ,'2020-07-20 00:54:10.857'				   --[DateCreated]
           ,0										   --[Deleted]
           ,'greenwerxlocaluuid'					   --[GUUID]
           ,'string'								   --[GuuidType]
           ,''										   --[Image]
           ,'Default Account UUID'					   --[Name]
           ,0										   --[NSFW]
           ,0										   --[Private]
           ,''										   --[RoleOperation]
           ,0										   --[RoleWeight]
           ,0										   --[SortOrder]
           ,''										   --[Status]
           ,'guid'									   --[UUIDType]
           ,'gwxlcl'								   --[UUParentID]
           ,'appid')								   --[UUParentIDType]
GO


